import HomeMain from '@/components/home'
import Head from 'next/head'
import { getSession } from "next-auth/react"


export default function Home() {
  return (
    <>
      <Head>
        <title>Authentication-Next-Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <HomeMain />
      </main>
    </>
  )
}

export async function getServerSideProps({req}){
 const session = await getSession({req})
 if(!session){
  return{
   redirect: {
    destination: '/login',
    permanent: false
   }
 }
 }
 return{
  props:{session}
 }
}

